### ISSUE TITLE
Small question about chain index shuffling

### ISSUE THREAD

**Issue by amorehead** [jasonkyuyim/se3_diffusion#10]
Hello. Thank you all for making this awesome project open-source and accessible to us all!

I had a quick question about the following dataloading logic. Is the following line supposed to reference `new_chain_idx` instead of `chain_idx`, since `new_chain_idx` represents the "shuffled" chain indices previously derived above this line?

https://github.com/jasonkyuyim/se3_diffusion/blob/ee15c31b755715855eae9622a9643233bb542d98/data/pdb_data_loader.py#L171

**Comment by jasonkyuyim** [comment]
Hi, Thanks for the kind words. Yes you're right, it should be `new_chain_idx`. This luckily doesn't affect our results since we trained on monomers which only had one chain. This feature and randomization is important when training on complexes. I've pushed a fix here https://github.com/jasonkyuyim/se3_diffusion/commit/fb350b69ca4349d7b29b19044ecc8627815dafce
